const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(__dirname+'/../local.reddit.home/plugin.js','utf8');
const factory=(x={})=>Object.assign({},x);
const privateUrl='https://www.reddit.com/.json?feed=SECRET&user=test';
const c={site:privateUrl,private_feed_url:'',feed_name:'',feedDisplayName:undefined,include_nsfw:'off',include_subreddit:'on',include_flair:'on',initial_history:'100',Identity:{createWithName:name=>factory({name})},Annotation:{createWithText:text=>factory({text})},Item:{createWithUriDate:(uri,date)=>factory({uri,date})},MediaAttachment:{createWithUrl:url=>factory({url})},LinkAttachment:{createWithUrl:url=>factory({url})},getItem:()=>null,setItem(){},processResults(){},processError:e=>{throw e},processVerification(){},sendRequest:()=>Promise.reject(Error('network disabled')),sendConditionalRequest:()=>Promise.reject(Error('network disabled')),Promise,Error,Date,JSON,Math,String,Array,RegExp,parseInt,isNaN,encodeURIComponent,encodeURI};
vm.createContext(c);vm.runInContext(source,c);
assert.equal(c.normalizedPrivateUrl(),privateUrl);
assert.equal(c.listingPageUrl(privateUrl,null),privateUrl+'&raw_json=1&limit=100');
assert.equal(c.listingPageUrl(privateUrl,'t3_abc'),privateUrl+'&raw_json=1&limit=100&after=t3_abc');
assert.equal(c.feedDisplayName(),'Reddit · Private Feed');
c.feed_name='Saved';assert.equal(c.feedDisplayName(),'Reddit · Saved');c.feed_name='';
const post={id:'abc',name:'t3_abc',title:'Example',author:'alice',created_utc:1700000000,permalink:'/r/test/comments/abc/example/',subreddit:'test',subreddit_name_prefixed:'r/test',selftext_html:'&lt;p&gt;Hello&lt;/p&gt;',score:1234,num_comments:56,is_self:true,over_18:false,link_flair_text:'News'};
const item=c.itemForData(post);
assert.equal(item.title,'Example');
assert.equal(item.author.name,'u/alice');
assert.equal(item.annotations.length,1);
assert.equal(item.annotations[0].text,'News in r/test');
assert.equal(item.annotations[0].uri,'https://www.reddit.com/r/test');
assert.ok(item.body.startsWith('<p class="reddit-meta-metrics"><small>1.2k points · 56 comments</small></p>'));
assert.ok(item.body.includes('<p>Hello</p>'));
assert.ok(item.body.indexOf('reddit-meta-metrics') < item.body.indexOf('<p>Hello</p>'));
const pinned=c.itemForData({...post,stickied:true});
assert.equal(pinned.annotations.length,2);
assert.equal(pinned.annotations[1].text,'Pinned');
c.include_flair='off';
assert.equal(c.itemForData(post).annotations[0].text,'r/test');
c.include_flair='on';c.include_subreddit='off';
assert.equal(c.itemForData(post).annotations,undefined);
c.include_subreddit='on';
const nsfwPost={...post,id:'nsfw',name:'t3_nsfw',over_18:true};
assert.equal(c.acceptedChildCount([{data:post},{data:nsfwPost},{data:post}],100),1);
assert.equal(c.itemsForChildren([{data:post},{data:nsfwPost},{data:post}],100).length,1);
c.site='https://www.reddit.com/r/test/new.json';assert.throws(()=>c.normalizedPrivateUrl(),/private JSON URL/);
c.site='';c.private_feed_url=privateUrl;assert.equal(c.normalizedPrivateUrl(),privateUrl);
c.site=privateUrl;c.private_feed_url='https://www.reddit.com/.json?feed=OLD';assert.equal(c.normalizedPrivateUrl(),privateUrl);
(async()=>{
  c.sendRequest=()=>Promise.resolve(JSON.stringify({status:200,body:JSON.stringify({data:{children:[]}})}));
  assert.equal((await c.requestListing(privateUrl,false)).data.children.length,0);
  c.sendConditionalRequest=()=>Promise.resolve(JSON.stringify({status:304,body:''}));
  assert.equal(await c.requestListing(privateUrl,true),null);
  assert.equal(await c.fetchListingPages(privateUrl,1,true,100),null);
  c.sendRequest=()=>Promise.resolve(JSON.stringify({status:403,body:''}));
  await assert.rejects(()=>c.requestListing(privateUrl,false),/HTTP 403/);
  console.log('plugin tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
